run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  cyclop:
    max-complexity: 15
  
  dupl:
    threshold: 100
    
  errcheck:
    check-type-assertions: true
    check-blank: true
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      
  gocyclo:
    min-complexity: 15
    
  godot:
    scope: declarations
    capital: false
    
  gofumpt:
    extra-rules: true
    
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
        ignored-numbers: 
          - '0'
          - '1'
          - '2'
          - '3'
          - '10'
          - '100'
          - '1000'
          
  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      
  lll:
    line-length: 120
    
  misspell:
    locale: US
    
  nakedret:
    max-func-lines: 30
    
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
    
  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "disableStutteringCheck"
      - name: unused-parameter
        disabled: true
        
issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - dupl
        
    # Disable linters for generated code
    - path: types/
      linters:
        - all
        
    # Allow long lines in examples
    - path: examples/
      linters:
        - lll
        
  max-issues-per-linter: 0
  max-same-issues: 0