version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - copyloopvar  # replaces exportloopref in v2
    - forbidigo
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - mnd  # replaces gomnd in v2
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace

  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - mnd
          - goconst
          - dupl

      # Disable linters for generated code
      - path: types/
        linters:
          - all

      # Allow long lines in examples
      - path: examples/
        linters:
          - lll

  settings:
    cyclop:
      max-complexity: 15

    dupl:
      threshold: 100

    errcheck:
      check-type-assertions: true
      check-blank: true

    goconst:
      min-len: 3
      min-occurrences: 3

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc

    gocyclo:
      min-complexity: 15

    godot:
      scope: declarations
      capital: false

    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
        - "10"
        - "100"
        - "1000"

    gosec:
      excludes:
        - G204 # Subprocess launched with variable

    lll:
      line-length: 120

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

    revive:
      rules:
        - name: exported
          disabled: false
          arguments:
            - "disableStutteringCheck"
        - name: unused-parameter
          disabled: true



issues:
  max-issues-per-linter: 0
  max-same-issues: 0
