// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ocr

// Missing type stubs for dependencies that were filtered out but still referenced
// These are minimal definitions to satisfy the compiler

// ModelsPageResponse represents a page response
type ModelsPageResponse struct {
	// Add minimal fields as needed
}

// ModelsPaginationResponse represents pagination response
type ModelsPaginationResponse struct {
	// Add minimal fields as needed
}

// ModelsJobStatus represents job status
type ModelsJobStatus struct {
	// Add minimal fields as needed
}

// ResponseErrorCode represents error codes
type ResponseErrorCode string

// ResponseErrorMessage represents error messages
type ResponseErrorMessage string
