/*
OCR API

OCR API for processing PDF documents with Gemini LLM integration

API version: 1.0
Contact: support@clarivo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ocr

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UploadInitiateUploadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadInitiateUploadRequest{}

// UploadInitiateUploadRequest struct for UploadInitiateUploadRequest
type UploadInitiateUploadRequest struct {
	ContentType string `json:"content_type"`
	FileName    string `json:"file_name"`
	FileSize    *int32 `json:"file_size,omitempty"`
	// Option 2: Direct specification (will create template on-the-fly)
	Format       *string                `json:"format,omitempty"`
	Instructions *string                `json:"instructions,omitempty"`
	Schema       map[string]interface{} `json:"schema,omitempty"`
	// Option 1: Use existing template
	TemplateId *string `json:"template_id,omitempty"`
	Tier       *string `json:"tier,omitempty"`
}

type _UploadInitiateUploadRequest UploadInitiateUploadRequest

// NewUploadInitiateUploadRequest instantiates a new UploadInitiateUploadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadInitiateUploadRequest(contentType string, fileName string) *UploadInitiateUploadRequest {
	this := UploadInitiateUploadRequest{}
	this.ContentType = contentType
	this.FileName = fileName
	return &this
}

// NewUploadInitiateUploadRequestWithDefaults instantiates a new UploadInitiateUploadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadInitiateUploadRequestWithDefaults() *UploadInitiateUploadRequest {
	this := UploadInitiateUploadRequest{}
	return &this
}

// GetContentType returns the ContentType field value
func (o *UploadInitiateUploadRequest) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *UploadInitiateUploadRequest) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *UploadInitiateUploadRequest) SetContentType(v string) {
	o.ContentType = v
}

// GetFileName returns the FileName field value
func (o *UploadInitiateUploadRequest) GetFileName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value
// and a boolean to check if the value has been set.
func (o *UploadInitiateUploadRequest) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileName, true
}

// SetFileName sets field value
func (o *UploadInitiateUploadRequest) SetFileName(v string) {
	o.FileName = v
}

// GetFileSize returns the FileSize field value if set, zero value otherwise.
func (o *UploadInitiateUploadRequest) GetFileSize() int32 {
	if o == nil || IsNil(o.FileSize) {
		var ret int32
		return ret
	}
	return *o.FileSize
}

// GetFileSizeOk returns a tuple with the FileSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadInitiateUploadRequest) GetFileSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.FileSize) {
		return nil, false
	}
	return o.FileSize, true
}

// HasFileSize returns a boolean if a field has been set.
func (o *UploadInitiateUploadRequest) HasFileSize() bool {
	if o != nil && !IsNil(o.FileSize) {
		return true
	}

	return false
}

// SetFileSize gets a reference to the given int32 and assigns it to the FileSize field.
func (o *UploadInitiateUploadRequest) SetFileSize(v int32) {
	o.FileSize = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *UploadInitiateUploadRequest) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadInitiateUploadRequest) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *UploadInitiateUploadRequest) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *UploadInitiateUploadRequest) SetFormat(v string) {
	o.Format = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *UploadInitiateUploadRequest) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadInitiateUploadRequest) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *UploadInitiateUploadRequest) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *UploadInitiateUploadRequest) SetInstructions(v string) {
	o.Instructions = &v
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *UploadInitiateUploadRequest) GetSchema() map[string]interface{} {
	if o == nil || IsNil(o.Schema) {
		var ret map[string]interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadInitiateUploadRequest) GetSchemaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return map[string]interface{}{}, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *UploadInitiateUploadRequest) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given map[string]interface{} and assigns it to the Schema field.
func (o *UploadInitiateUploadRequest) SetSchema(v map[string]interface{}) {
	o.Schema = v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *UploadInitiateUploadRequest) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId) {
		var ret string
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadInitiateUploadRequest) GetTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *UploadInitiateUploadRequest) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given string and assigns it to the TemplateId field.
func (o *UploadInitiateUploadRequest) SetTemplateId(v string) {
	o.TemplateId = &v
}

// GetTier returns the Tier field value if set, zero value otherwise.
func (o *UploadInitiateUploadRequest) GetTier() string {
	if o == nil || IsNil(o.Tier) {
		var ret string
		return ret
	}
	return *o.Tier
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadInitiateUploadRequest) GetTierOk() (*string, bool) {
	if o == nil || IsNil(o.Tier) {
		return nil, false
	}
	return o.Tier, true
}

// HasTier returns a boolean if a field has been set.
func (o *UploadInitiateUploadRequest) HasTier() bool {
	if o != nil && !IsNil(o.Tier) {
		return true
	}

	return false
}

// SetTier gets a reference to the given string and assigns it to the Tier field.
func (o *UploadInitiateUploadRequest) SetTier(v string) {
	o.Tier = &v
}

func (o UploadInitiateUploadRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadInitiateUploadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content_type"] = o.ContentType
	toSerialize["file_name"] = o.FileName
	if !IsNil(o.FileSize) {
		toSerialize["file_size"] = o.FileSize
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	if !IsNil(o.Schema) {
		toSerialize["schema"] = o.Schema
	}
	if !IsNil(o.TemplateId) {
		toSerialize["template_id"] = o.TemplateId
	}
	if !IsNil(o.Tier) {
		toSerialize["tier"] = o.Tier
	}
	return toSerialize, nil
}

func (o *UploadInitiateUploadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content_type",
		"file_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadInitiateUploadRequest := _UploadInitiateUploadRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadInitiateUploadRequest)

	if err != nil {
		return err
	}

	*o = UploadInitiateUploadRequest(varUploadInitiateUploadRequest)

	return err
}

type NullableUploadInitiateUploadRequest struct {
	value *UploadInitiateUploadRequest
	isSet bool
}

func (v NullableUploadInitiateUploadRequest) Get() *UploadInitiateUploadRequest {
	return v.value
}

func (v *NullableUploadInitiateUploadRequest) Set(val *UploadInitiateUploadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadInitiateUploadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadInitiateUploadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadInitiateUploadRequest(val *UploadInitiateUploadRequest) *NullableUploadInitiateUploadRequest {
	return &NullableUploadInitiateUploadRequest{value: val, isSet: true}
}

func (v NullableUploadInitiateUploadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadInitiateUploadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
