/*
OCR API

OCR API for processing PDF documents with Gemini LLM integration

API version: 1.0
Contact: support@clarivo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ocr

import (
	"encoding/json"
)

// checks if the ModelsOCRStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsOCRStatusResponse{}

// ModelsOCRStatusResponse struct for ModelsOCRStatusResponse
type ModelsOCRStatusResponse struct {
	CompletedAt        *string  `json:"completed_at,omitempty"`
	ErrorMessage       *string  `json:"error_message,omitempty"`
	JobId              *string  `json:"job_id,omitempty"`
	ProcessedPages     *int32   `json:"processed_pages,omitempty"`
	ProgressPercentage *float32 `json:"progress_percentage,omitempty"`
	ResultFormat       *string  `json:"result_format,omitempty"`
	Status             *string  `json:"status,omitempty"`
	TotalPages         *int32   `json:"total_pages,omitempty"`
}

// NewModelsOCRStatusResponse instantiates a new ModelsOCRStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsOCRStatusResponse() *ModelsOCRStatusResponse {
	this := ModelsOCRStatusResponse{}
	return &this
}

// NewModelsOCRStatusResponseWithDefaults instantiates a new ModelsOCRStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsOCRStatusResponseWithDefaults() *ModelsOCRStatusResponse {
	this := ModelsOCRStatusResponse{}
	return &this
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise.
func (o *ModelsOCRStatusResponse) GetCompletedAt() string {
	if o == nil || IsNil(o.CompletedAt) {
		var ret string
		return ret
	}
	return *o.CompletedAt
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsOCRStatusResponse) GetCompletedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CompletedAt) {
		return nil, false
	}
	return o.CompletedAt, true
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *ModelsOCRStatusResponse) HasCompletedAt() bool {
	if o != nil && !IsNil(o.CompletedAt) {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given string and assigns it to the CompletedAt field.
func (o *ModelsOCRStatusResponse) SetCompletedAt(v string) {
	o.CompletedAt = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *ModelsOCRStatusResponse) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsOCRStatusResponse) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *ModelsOCRStatusResponse) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *ModelsOCRStatusResponse) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *ModelsOCRStatusResponse) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsOCRStatusResponse) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *ModelsOCRStatusResponse) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *ModelsOCRStatusResponse) SetJobId(v string) {
	o.JobId = &v
}

// GetProcessedPages returns the ProcessedPages field value if set, zero value otherwise.
func (o *ModelsOCRStatusResponse) GetProcessedPages() int32 {
	if o == nil || IsNil(o.ProcessedPages) {
		var ret int32
		return ret
	}
	return *o.ProcessedPages
}

// GetProcessedPagesOk returns a tuple with the ProcessedPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsOCRStatusResponse) GetProcessedPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.ProcessedPages) {
		return nil, false
	}
	return o.ProcessedPages, true
}

// HasProcessedPages returns a boolean if a field has been set.
func (o *ModelsOCRStatusResponse) HasProcessedPages() bool {
	if o != nil && !IsNil(o.ProcessedPages) {
		return true
	}

	return false
}

// SetProcessedPages gets a reference to the given int32 and assigns it to the ProcessedPages field.
func (o *ModelsOCRStatusResponse) SetProcessedPages(v int32) {
	o.ProcessedPages = &v
}

// GetProgressPercentage returns the ProgressPercentage field value if set, zero value otherwise.
func (o *ModelsOCRStatusResponse) GetProgressPercentage() float32 {
	if o == nil || IsNil(o.ProgressPercentage) {
		var ret float32
		return ret
	}
	return *o.ProgressPercentage
}

// GetProgressPercentageOk returns a tuple with the ProgressPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsOCRStatusResponse) GetProgressPercentageOk() (*float32, bool) {
	if o == nil || IsNil(o.ProgressPercentage) {
		return nil, false
	}
	return o.ProgressPercentage, true
}

// HasProgressPercentage returns a boolean if a field has been set.
func (o *ModelsOCRStatusResponse) HasProgressPercentage() bool {
	if o != nil && !IsNil(o.ProgressPercentage) {
		return true
	}

	return false
}

// SetProgressPercentage gets a reference to the given float32 and assigns it to the ProgressPercentage field.
func (o *ModelsOCRStatusResponse) SetProgressPercentage(v float32) {
	o.ProgressPercentage = &v
}

// GetResultFormat returns the ResultFormat field value if set, zero value otherwise.
func (o *ModelsOCRStatusResponse) GetResultFormat() string {
	if o == nil || IsNil(o.ResultFormat) {
		var ret string
		return ret
	}
	return *o.ResultFormat
}

// GetResultFormatOk returns a tuple with the ResultFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsOCRStatusResponse) GetResultFormatOk() (*string, bool) {
	if o == nil || IsNil(o.ResultFormat) {
		return nil, false
	}
	return o.ResultFormat, true
}

// HasResultFormat returns a boolean if a field has been set.
func (o *ModelsOCRStatusResponse) HasResultFormat() bool {
	if o != nil && !IsNil(o.ResultFormat) {
		return true
	}

	return false
}

// SetResultFormat gets a reference to the given string and assigns it to the ResultFormat field.
func (o *ModelsOCRStatusResponse) SetResultFormat(v string) {
	o.ResultFormat = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ModelsOCRStatusResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsOCRStatusResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ModelsOCRStatusResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ModelsOCRStatusResponse) SetStatus(v string) {
	o.Status = &v
}

// GetTotalPages returns the TotalPages field value if set, zero value otherwise.
func (o *ModelsOCRStatusResponse) GetTotalPages() int32 {
	if o == nil || IsNil(o.TotalPages) {
		var ret int32
		return ret
	}
	return *o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsOCRStatusResponse) GetTotalPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalPages) {
		return nil, false
	}
	return o.TotalPages, true
}

// HasTotalPages returns a boolean if a field has been set.
func (o *ModelsOCRStatusResponse) HasTotalPages() bool {
	if o != nil && !IsNil(o.TotalPages) {
		return true
	}

	return false
}

// SetTotalPages gets a reference to the given int32 and assigns it to the TotalPages field.
func (o *ModelsOCRStatusResponse) SetTotalPages(v int32) {
	o.TotalPages = &v
}

func (o ModelsOCRStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsOCRStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CompletedAt) {
		toSerialize["completed_at"] = o.CompletedAt
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["error_message"] = o.ErrorMessage
	}
	if !IsNil(o.JobId) {
		toSerialize["job_id"] = o.JobId
	}
	if !IsNil(o.ProcessedPages) {
		toSerialize["processed_pages"] = o.ProcessedPages
	}
	if !IsNil(o.ProgressPercentage) {
		toSerialize["progress_percentage"] = o.ProgressPercentage
	}
	if !IsNil(o.ResultFormat) {
		toSerialize["result_format"] = o.ResultFormat
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TotalPages) {
		toSerialize["total_pages"] = o.TotalPages
	}
	return toSerialize, nil
}

type NullableModelsOCRStatusResponse struct {
	value *ModelsOCRStatusResponse
	isSet bool
}

func (v NullableModelsOCRStatusResponse) Get() *ModelsOCRStatusResponse {
	return v.value
}

func (v *NullableModelsOCRStatusResponse) Set(val *ModelsOCRStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsOCRStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsOCRStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsOCRStatusResponse(val *ModelsOCRStatusResponse) *NullableModelsOCRStatusResponse {
	return &NullableModelsOCRStatusResponse{value: val, isSet: true}
}

func (v NullableModelsOCRStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsOCRStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
