/*
OCR API

OCR API for processing PDF documents with Gemini LLM integration

API version: 1.0
Contact: support@clarivo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ocr

import (
	"encoding/json"
	"time"
)

// checks if the UploadPresignedUploadResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadPresignedUploadResponse{}

// UploadPresignedUploadResponse struct for UploadPresignedUploadResponse
type UploadPresignedUploadResponse struct {
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	JobId     *string    `json:"job_id,omitempty"`
	UploadId  *string    `json:"upload_id,omitempty"`
	UploadUrl *string    `json:"upload_url,omitempty"`
}

// NewUploadPresignedUploadResponse instantiates a new UploadPresignedUploadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadPresignedUploadResponse() *UploadPresignedUploadResponse {
	this := UploadPresignedUploadResponse{}
	return &this
}

// NewUploadPresignedUploadResponseWithDefaults instantiates a new UploadPresignedUploadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadPresignedUploadResponseWithDefaults() *UploadPresignedUploadResponse {
	this := UploadPresignedUploadResponse{}
	return &this
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *UploadPresignedUploadResponse) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadPresignedUploadResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *UploadPresignedUploadResponse) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *UploadPresignedUploadResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *UploadPresignedUploadResponse) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadPresignedUploadResponse) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *UploadPresignedUploadResponse) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *UploadPresignedUploadResponse) SetJobId(v string) {
	o.JobId = &v
}

// GetUploadId returns the UploadId field value if set, zero value otherwise.
func (o *UploadPresignedUploadResponse) GetUploadId() string {
	if o == nil || IsNil(o.UploadId) {
		var ret string
		return ret
	}
	return *o.UploadId
}

// GetUploadIdOk returns a tuple with the UploadId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadPresignedUploadResponse) GetUploadIdOk() (*string, bool) {
	if o == nil || IsNil(o.UploadId) {
		return nil, false
	}
	return o.UploadId, true
}

// HasUploadId returns a boolean if a field has been set.
func (o *UploadPresignedUploadResponse) HasUploadId() bool {
	if o != nil && !IsNil(o.UploadId) {
		return true
	}

	return false
}

// SetUploadId gets a reference to the given string and assigns it to the UploadId field.
func (o *UploadPresignedUploadResponse) SetUploadId(v string) {
	o.UploadId = &v
}

// GetUploadUrl returns the UploadUrl field value if set, zero value otherwise.
func (o *UploadPresignedUploadResponse) GetUploadUrl() string {
	if o == nil || IsNil(o.UploadUrl) {
		var ret string
		return ret
	}
	return *o.UploadUrl
}

// GetUploadUrlOk returns a tuple with the UploadUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadPresignedUploadResponse) GetUploadUrlOk() (*string, bool) {
	if o == nil || IsNil(o.UploadUrl) {
		return nil, false
	}
	return o.UploadUrl, true
}

// HasUploadUrl returns a boolean if a field has been set.
func (o *UploadPresignedUploadResponse) HasUploadUrl() bool {
	if o != nil && !IsNil(o.UploadUrl) {
		return true
	}

	return false
}

// SetUploadUrl gets a reference to the given string and assigns it to the UploadUrl field.
func (o *UploadPresignedUploadResponse) SetUploadUrl(v string) {
	o.UploadUrl = &v
}

func (o UploadPresignedUploadResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadPresignedUploadResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.JobId) {
		toSerialize["job_id"] = o.JobId
	}
	if !IsNil(o.UploadId) {
		toSerialize["upload_id"] = o.UploadId
	}
	if !IsNil(o.UploadUrl) {
		toSerialize["upload_url"] = o.UploadUrl
	}
	return toSerialize, nil
}

type NullableUploadPresignedUploadResponse struct {
	value *UploadPresignedUploadResponse
	isSet bool
}

func (v NullableUploadPresignedUploadResponse) Get() *UploadPresignedUploadResponse {
	return v.value
}

func (v *NullableUploadPresignedUploadResponse) Set(val *UploadPresignedUploadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadPresignedUploadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadPresignedUploadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadPresignedUploadResponse(val *UploadPresignedUploadResponse) *NullableUploadPresignedUploadResponse {
	return &NullableUploadPresignedUploadResponse{value: val, isSet: true}
}

func (v NullableUploadPresignedUploadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadPresignedUploadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
