/*
OCR API

OCR API for processing PDF documents with Gemini LLM integration

API version: 1.0
Contact: support@clarivo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ocr

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UploadURLUploadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadURLUploadRequest{}

// UploadURLUploadRequest struct for UploadURLUploadRequest
type UploadURLUploadRequest struct {
	FileName *string `json:"file_name,omitempty"`
	// Option 2: Direct specification (will create template on-the-fly)
	Format       *string                `json:"format,omitempty"`
	Instructions *string                `json:"instructions,omitempty"`
	Schema       map[string]interface{} `json:"schema,omitempty"`
	// Option 1: Use existing template
	TemplateId *string `json:"template_id,omitempty"`
	Tier       *string `json:"tier,omitempty"`
	Url        string  `json:"url"`
}

type _UploadURLUploadRequest UploadURLUploadRequest

// NewUploadURLUploadRequest instantiates a new UploadURLUploadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadURLUploadRequest(url string) *UploadURLUploadRequest {
	this := UploadURLUploadRequest{}
	this.Url = url
	return &this
}

// NewUploadURLUploadRequestWithDefaults instantiates a new UploadURLUploadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadURLUploadRequestWithDefaults() *UploadURLUploadRequest {
	this := UploadURLUploadRequest{}
	return &this
}

// GetFileName returns the FileName field value if set, zero value otherwise.
func (o *UploadURLUploadRequest) GetFileName() string {
	if o == nil || IsNil(o.FileName) {
		var ret string
		return ret
	}
	return *o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadURLUploadRequest) GetFileNameOk() (*string, bool) {
	if o == nil || IsNil(o.FileName) {
		return nil, false
	}
	return o.FileName, true
}

// HasFileName returns a boolean if a field has been set.
func (o *UploadURLUploadRequest) HasFileName() bool {
	if o != nil && !IsNil(o.FileName) {
		return true
	}

	return false
}

// SetFileName gets a reference to the given string and assigns it to the FileName field.
func (o *UploadURLUploadRequest) SetFileName(v string) {
	o.FileName = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *UploadURLUploadRequest) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadURLUploadRequest) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *UploadURLUploadRequest) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *UploadURLUploadRequest) SetFormat(v string) {
	o.Format = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *UploadURLUploadRequest) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadURLUploadRequest) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *UploadURLUploadRequest) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *UploadURLUploadRequest) SetInstructions(v string) {
	o.Instructions = &v
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *UploadURLUploadRequest) GetSchema() map[string]interface{} {
	if o == nil || IsNil(o.Schema) {
		var ret map[string]interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadURLUploadRequest) GetSchemaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return map[string]interface{}{}, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *UploadURLUploadRequest) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given map[string]interface{} and assigns it to the Schema field.
func (o *UploadURLUploadRequest) SetSchema(v map[string]interface{}) {
	o.Schema = v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *UploadURLUploadRequest) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId) {
		var ret string
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadURLUploadRequest) GetTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *UploadURLUploadRequest) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given string and assigns it to the TemplateId field.
func (o *UploadURLUploadRequest) SetTemplateId(v string) {
	o.TemplateId = &v
}

// GetTier returns the Tier field value if set, zero value otherwise.
func (o *UploadURLUploadRequest) GetTier() string {
	if o == nil || IsNil(o.Tier) {
		var ret string
		return ret
	}
	return *o.Tier
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadURLUploadRequest) GetTierOk() (*string, bool) {
	if o == nil || IsNil(o.Tier) {
		return nil, false
	}
	return o.Tier, true
}

// HasTier returns a boolean if a field has been set.
func (o *UploadURLUploadRequest) HasTier() bool {
	if o != nil && !IsNil(o.Tier) {
		return true
	}

	return false
}

// SetTier gets a reference to the given string and assigns it to the Tier field.
func (o *UploadURLUploadRequest) SetTier(v string) {
	o.Tier = &v
}

// GetUrl returns the Url field value
func (o *UploadURLUploadRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *UploadURLUploadRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *UploadURLUploadRequest) SetUrl(v string) {
	o.Url = v
}

func (o UploadURLUploadRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadURLUploadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FileName) {
		toSerialize["file_name"] = o.FileName
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	if !IsNil(o.Schema) {
		toSerialize["schema"] = o.Schema
	}
	if !IsNil(o.TemplateId) {
		toSerialize["template_id"] = o.TemplateId
	}
	if !IsNil(o.Tier) {
		toSerialize["tier"] = o.Tier
	}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *UploadURLUploadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadURLUploadRequest := _UploadURLUploadRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadURLUploadRequest)

	if err != nil {
		return err
	}

	*o = UploadURLUploadRequest(varUploadURLUploadRequest)

	return err
}

type NullableUploadURLUploadRequest struct {
	value *UploadURLUploadRequest
	isSet bool
}

func (v NullableUploadURLUploadRequest) Get() *UploadURLUploadRequest {
	return v.value
}

func (v *NullableUploadURLUploadRequest) Set(val *UploadURLUploadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadURLUploadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadURLUploadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadURLUploadRequest(val *UploadURLUploadRequest) *NullableUploadURLUploadRequest {
	return &NullableUploadURLUploadRequest{value: val, isSet: true}
}

func (v NullableUploadURLUploadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadURLUploadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
