/*
LeapOCR API

Provide your JWT token via the `Authorization` header. Example: Authorization: Bearer <token>

API version: v1
Contact: support@leapocr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
)

// checks if the ResponseErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseErrorResponse{}

// ResponseErrorResponse struct for ResponseErrorResponse
type ResponseErrorResponse struct {
	Code    *string               `json:"code,omitempty"`
	Details interface{}           `json:"details,omitempty"`
	Error   *ResponseErrorMessage `json:"error,omitempty"`
}

// NewResponseErrorResponse instantiates a new ResponseErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseErrorResponse() *ResponseErrorResponse {
	this := ResponseErrorResponse{}
	return &this
}

// NewResponseErrorResponseWithDefaults instantiates a new ResponseErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseErrorResponseWithDefaults() *ResponseErrorResponse {
	this := ResponseErrorResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ResponseErrorResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseErrorResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ResponseErrorResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ResponseErrorResponse) SetCode(v string) {
	o.Code = &v
}

// GetDetails returns the Details field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponseErrorResponse) GetDetails() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseErrorResponse) GetDetailsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return &o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *ResponseErrorResponse) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given interface{} and assigns it to the Details field.
func (o *ResponseErrorResponse) SetDetails(v interface{}) {
	o.Details = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ResponseErrorResponse) GetError() ResponseErrorMessage {
	if o == nil || IsNil(o.Error) {
		var ret ResponseErrorMessage
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseErrorResponse) GetErrorOk() (*ResponseErrorMessage, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ResponseErrorResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given ResponseErrorMessage and assigns it to the Error field.
func (o *ResponseErrorResponse) SetError(v ResponseErrorMessage) {
	o.Error = &v
}

func (o ResponseErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if o.Details != nil {
		toSerialize["details"] = o.Details
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableResponseErrorResponse struct {
	value *ResponseErrorResponse
	isSet bool
}

func (v NullableResponseErrorResponse) Get() *ResponseErrorResponse {
	return v.value
}

func (v *NullableResponseErrorResponse) Set(val *ResponseErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseErrorResponse(val *ResponseErrorResponse) *NullableResponseErrorResponse {
	return &NullableResponseErrorResponse{value: val, isSet: true}
}

func (v NullableResponseErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
