/*
LeapOCR API

Provide your JWT token via the `Authorization` header. Example: Authorization: Bearer <token>

API version: v1
Contact: support@leapocr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TemplatesUpdateTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplatesUpdateTemplateRequest{}

// TemplatesUpdateTemplateRequest struct for TemplatesUpdateTemplateRequest
type TemplatesUpdateTemplateRequest struct {
	Color        *string `json:"color,omitempty"`
	Description  *string `json:"description,omitempty"`
	Enabled      *bool   `json:"enabled,omitempty"`
	Favorite     *bool   `json:"favorite,omitempty"`
	Format       string  `json:"format"`
	Instructions *string `json:"instructions,omitempty"`
	Name         string  `json:"name"`
	// JSON schema definition
	Schema map[string]interface{} `json:"schema,omitempty"`
	Tags   []string               `json:"tags,omitempty"`
}

type _TemplatesUpdateTemplateRequest TemplatesUpdateTemplateRequest

// NewTemplatesUpdateTemplateRequest instantiates a new TemplatesUpdateTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplatesUpdateTemplateRequest(format string, name string) *TemplatesUpdateTemplateRequest {
	this := TemplatesUpdateTemplateRequest{}
	this.Format = format
	this.Name = name
	return &this
}

// NewTemplatesUpdateTemplateRequestWithDefaults instantiates a new TemplatesUpdateTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplatesUpdateTemplateRequestWithDefaults() *TemplatesUpdateTemplateRequest {
	this := TemplatesUpdateTemplateRequest{}
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *TemplatesUpdateTemplateRequest) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatesUpdateTemplateRequest) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *TemplatesUpdateTemplateRequest) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *TemplatesUpdateTemplateRequest) SetColor(v string) {
	o.Color = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TemplatesUpdateTemplateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatesUpdateTemplateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TemplatesUpdateTemplateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TemplatesUpdateTemplateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *TemplatesUpdateTemplateRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatesUpdateTemplateRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *TemplatesUpdateTemplateRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *TemplatesUpdateTemplateRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetFavorite returns the Favorite field value if set, zero value otherwise.
func (o *TemplatesUpdateTemplateRequest) GetFavorite() bool {
	if o == nil || IsNil(o.Favorite) {
		var ret bool
		return ret
	}
	return *o.Favorite
}

// GetFavoriteOk returns a tuple with the Favorite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatesUpdateTemplateRequest) GetFavoriteOk() (*bool, bool) {
	if o == nil || IsNil(o.Favorite) {
		return nil, false
	}
	return o.Favorite, true
}

// HasFavorite returns a boolean if a field has been set.
func (o *TemplatesUpdateTemplateRequest) HasFavorite() bool {
	if o != nil && !IsNil(o.Favorite) {
		return true
	}

	return false
}

// SetFavorite gets a reference to the given bool and assigns it to the Favorite field.
func (o *TemplatesUpdateTemplateRequest) SetFavorite(v bool) {
	o.Favorite = &v
}

// GetFormat returns the Format field value
func (o *TemplatesUpdateTemplateRequest) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *TemplatesUpdateTemplateRequest) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *TemplatesUpdateTemplateRequest) SetFormat(v string) {
	o.Format = v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *TemplatesUpdateTemplateRequest) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatesUpdateTemplateRequest) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *TemplatesUpdateTemplateRequest) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *TemplatesUpdateTemplateRequest) SetInstructions(v string) {
	o.Instructions = &v
}

// GetName returns the Name field value
func (o *TemplatesUpdateTemplateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TemplatesUpdateTemplateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TemplatesUpdateTemplateRequest) SetName(v string) {
	o.Name = v
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *TemplatesUpdateTemplateRequest) GetSchema() map[string]interface{} {
	if o == nil || IsNil(o.Schema) {
		var ret map[string]interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatesUpdateTemplateRequest) GetSchemaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return map[string]interface{}{}, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *TemplatesUpdateTemplateRequest) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given map[string]interface{} and assigns it to the Schema field.
func (o *TemplatesUpdateTemplateRequest) SetSchema(v map[string]interface{}) {
	o.Schema = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *TemplatesUpdateTemplateRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatesUpdateTemplateRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *TemplatesUpdateTemplateRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *TemplatesUpdateTemplateRequest) SetTags(v []string) {
	o.Tags = v
}

func (o TemplatesUpdateTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplatesUpdateTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Favorite) {
		toSerialize["favorite"] = o.Favorite
	}
	toSerialize["format"] = o.Format
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Schema) {
		toSerialize["schema"] = o.Schema
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

func (o *TemplatesUpdateTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"format",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplatesUpdateTemplateRequest := _TemplatesUpdateTemplateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplatesUpdateTemplateRequest)

	if err != nil {
		return err
	}

	*o = TemplatesUpdateTemplateRequest(varTemplatesUpdateTemplateRequest)

	return err
}

type NullableTemplatesUpdateTemplateRequest struct {
	value *TemplatesUpdateTemplateRequest
	isSet bool
}

func (v NullableTemplatesUpdateTemplateRequest) Get() *TemplatesUpdateTemplateRequest {
	return v.value
}

func (v *NullableTemplatesUpdateTemplateRequest) Set(val *TemplatesUpdateTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplatesUpdateTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplatesUpdateTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplatesUpdateTemplateRequest(val *TemplatesUpdateTemplateRequest) *NullableTemplatesUpdateTemplateRequest {
	return &NullableTemplatesUpdateTemplateRequest{value: val, isSet: true}
}

func (v NullableTemplatesUpdateTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplatesUpdateTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
