/*
LeapOCR API

Provide your JWT token via the `Authorization` header. Example: Authorization: Bearer <token>

API version: v1
Contact: support@leapocr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UploadDirectUploadCompleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadDirectUploadCompleteRequest{}

// UploadDirectUploadCompleteRequest struct for UploadDirectUploadCompleteRequest
type UploadDirectUploadCompleteRequest struct {
	Parts []UploadCompletedPart `json:"parts"`
}

type _UploadDirectUploadCompleteRequest UploadDirectUploadCompleteRequest

// NewUploadDirectUploadCompleteRequest instantiates a new UploadDirectUploadCompleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadDirectUploadCompleteRequest(parts []UploadCompletedPart) *UploadDirectUploadCompleteRequest {
	this := UploadDirectUploadCompleteRequest{}
	this.Parts = parts
	return &this
}

// NewUploadDirectUploadCompleteRequestWithDefaults instantiates a new UploadDirectUploadCompleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadDirectUploadCompleteRequestWithDefaults() *UploadDirectUploadCompleteRequest {
	this := UploadDirectUploadCompleteRequest{}
	return &this
}

// GetParts returns the Parts field value
func (o *UploadDirectUploadCompleteRequest) GetParts() []UploadCompletedPart {
	if o == nil {
		var ret []UploadCompletedPart
		return ret
	}

	return o.Parts
}

// GetPartsOk returns a tuple with the Parts field value
// and a boolean to check if the value has been set.
func (o *UploadDirectUploadCompleteRequest) GetPartsOk() ([]UploadCompletedPart, bool) {
	if o == nil {
		return nil, false
	}
	return o.Parts, true
}

// SetParts sets field value
func (o *UploadDirectUploadCompleteRequest) SetParts(v []UploadCompletedPart) {
	o.Parts = v
}

func (o UploadDirectUploadCompleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadDirectUploadCompleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parts"] = o.Parts
	return toSerialize, nil
}

func (o *UploadDirectUploadCompleteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"parts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadDirectUploadCompleteRequest := _UploadDirectUploadCompleteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadDirectUploadCompleteRequest)

	if err != nil {
		return err
	}

	*o = UploadDirectUploadCompleteRequest(varUploadDirectUploadCompleteRequest)

	return err
}

type NullableUploadDirectUploadCompleteRequest struct {
	value *UploadDirectUploadCompleteRequest
	isSet bool
}

func (v NullableUploadDirectUploadCompleteRequest) Get() *UploadDirectUploadCompleteRequest {
	return v.value
}

func (v *NullableUploadDirectUploadCompleteRequest) Set(val *UploadDirectUploadCompleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadDirectUploadCompleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadDirectUploadCompleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadDirectUploadCompleteRequest(val *UploadDirectUploadCompleteRequest) *NullableUploadDirectUploadCompleteRequest {
	return &NullableUploadDirectUploadCompleteRequest{value: val, isSet: true}
}

func (v NullableUploadDirectUploadCompleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadDirectUploadCompleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
