/*
LeapOCR API

Provide your JWT token via the `Authorization` header. Example: Authorization: Bearer <token>

API version: v1
Contact: support@leapocr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
)

// checks if the CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse{}

// CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse struct for CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse
type CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse struct {
	Pagination   *CreditsPaginationInfo                    `json:"pagination,omitempty"`
	Transactions []CreditsCreditTransactionProjectResponse `json:"transactions,omitempty"`
}

// NewCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse instantiates a new CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse() *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse {
	this := CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse{}
	return &this
}

// NewCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponseWithDefaults instantiates a new CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponseWithDefaults() *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse {
	this := CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse{}
	return &this
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) GetPagination() CreditsPaginationInfo {
	if o == nil || IsNil(o.Pagination) {
		var ret CreditsPaginationInfo
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) GetPaginationOk() (*CreditsPaginationInfo, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given CreditsPaginationInfo and assigns it to the Pagination field.
func (o *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) SetPagination(v CreditsPaginationInfo) {
	o.Pagination = &v
}

// GetTransactions returns the Transactions field value if set, zero value otherwise.
func (o *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) GetTransactions() []CreditsCreditTransactionProjectResponse {
	if o == nil || IsNil(o.Transactions) {
		var ret []CreditsCreditTransactionProjectResponse
		return ret
	}
	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) GetTransactionsOk() ([]CreditsCreditTransactionProjectResponse, bool) {
	if o == nil || IsNil(o.Transactions) {
		return nil, false
	}
	return o.Transactions, true
}

// HasTransactions returns a boolean if a field has been set.
func (o *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) HasTransactions() bool {
	if o != nil && !IsNil(o.Transactions) {
		return true
	}

	return false
}

// SetTransactions gets a reference to the given []CreditsCreditTransactionProjectResponse and assigns it to the Transactions field.
func (o *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) SetTransactions(v []CreditsCreditTransactionProjectResponse) {
	o.Transactions = v
}

func (o CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	if !IsNil(o.Transactions) {
		toSerialize["transactions"] = o.Transactions
	}
	return toSerialize, nil
}

type NullableCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse struct {
	value *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse
	isSet bool
}

func (v NullableCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) Get() *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse {
	return v.value
}

func (v *NullableCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) Set(val *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse(val *CreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) *NullableCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse {
	return &NullableCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse{value: val, isSet: true}
}

func (v NullableCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditsCreditTransactionsResponseCreditsCreditTransactionProjectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
