/*
LeapOCR API

Provide your JWT token via the `Authorization` header. Example: Authorization: Bearer <token>

API version: v1
Contact: support@leapocr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
)

// checks if the CreditsCatalogBenefit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditsCatalogBenefit{}

// CreditsCatalogBenefit struct for CreditsCatalogBenefit
type CreditsCatalogBenefit struct {
	Description *string `json:"description,omitempty"`
	Units       *int32  `json:"units,omitempty"`
}

// NewCreditsCatalogBenefit instantiates a new CreditsCatalogBenefit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditsCatalogBenefit() *CreditsCatalogBenefit {
	this := CreditsCatalogBenefit{}
	return &this
}

// NewCreditsCatalogBenefitWithDefaults instantiates a new CreditsCatalogBenefit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditsCatalogBenefitWithDefaults() *CreditsCatalogBenefit {
	this := CreditsCatalogBenefit{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreditsCatalogBenefit) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditsCatalogBenefit) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreditsCatalogBenefit) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreditsCatalogBenefit) SetDescription(v string) {
	o.Description = &v
}

// GetUnits returns the Units field value if set, zero value otherwise.
func (o *CreditsCatalogBenefit) GetUnits() int32 {
	if o == nil || IsNil(o.Units) {
		var ret int32
		return ret
	}
	return *o.Units
}

// GetUnitsOk returns a tuple with the Units field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditsCatalogBenefit) GetUnitsOk() (*int32, bool) {
	if o == nil || IsNil(o.Units) {
		return nil, false
	}
	return o.Units, true
}

// HasUnits returns a boolean if a field has been set.
func (o *CreditsCatalogBenefit) HasUnits() bool {
	if o != nil && !IsNil(o.Units) {
		return true
	}

	return false
}

// SetUnits gets a reference to the given int32 and assigns it to the Units field.
func (o *CreditsCatalogBenefit) SetUnits(v int32) {
	o.Units = &v
}

func (o CreditsCatalogBenefit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditsCatalogBenefit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Units) {
		toSerialize["units"] = o.Units
	}
	return toSerialize, nil
}

type NullableCreditsCatalogBenefit struct {
	value *CreditsCatalogBenefit
	isSet bool
}

func (v NullableCreditsCatalogBenefit) Get() *CreditsCatalogBenefit {
	return v.value
}

func (v *NullableCreditsCatalogBenefit) Set(val *CreditsCatalogBenefit) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditsCatalogBenefit) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditsCatalogBenefit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditsCatalogBenefit(val *CreditsCatalogBenefit) *NullableCreditsCatalogBenefit {
	return &NullableCreditsCatalogBenefit{value: val, isSet: true}
}

func (v NullableCreditsCatalogBenefit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditsCatalogBenefit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
