/*
LeapOCR API

Provide your JWT token via the `Authorization` header. Example: Authorization: Bearer <token>

API version: v1
Contact: support@leapocr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
)

// checks if the JobsRestartJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobsRestartJobRequest{}

// JobsRestartJobRequest struct for JobsRestartJobRequest
type JobsRestartJobRequest struct {
	// Force restart even for completed jobs
	Force *bool `json:"force,omitempty"`
	// Keep existing progress when restarting
	PreserveProgress *bool `json:"preserve_progress,omitempty"`
}

// NewJobsRestartJobRequest instantiates a new JobsRestartJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobsRestartJobRequest() *JobsRestartJobRequest {
	this := JobsRestartJobRequest{}
	return &this
}

// NewJobsRestartJobRequestWithDefaults instantiates a new JobsRestartJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobsRestartJobRequestWithDefaults() *JobsRestartJobRequest {
	this := JobsRestartJobRequest{}
	return &this
}

// GetForce returns the Force field value if set, zero value otherwise.
func (o *JobsRestartJobRequest) GetForce() bool {
	if o == nil || IsNil(o.Force) {
		var ret bool
		return ret
	}
	return *o.Force
}

// GetForceOk returns a tuple with the Force field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsRestartJobRequest) GetForceOk() (*bool, bool) {
	if o == nil || IsNil(o.Force) {
		return nil, false
	}
	return o.Force, true
}

// HasForce returns a boolean if a field has been set.
func (o *JobsRestartJobRequest) HasForce() bool {
	if o != nil && !IsNil(o.Force) {
		return true
	}

	return false
}

// SetForce gets a reference to the given bool and assigns it to the Force field.
func (o *JobsRestartJobRequest) SetForce(v bool) {
	o.Force = &v
}

// GetPreserveProgress returns the PreserveProgress field value if set, zero value otherwise.
func (o *JobsRestartJobRequest) GetPreserveProgress() bool {
	if o == nil || IsNil(o.PreserveProgress) {
		var ret bool
		return ret
	}
	return *o.PreserveProgress
}

// GetPreserveProgressOk returns a tuple with the PreserveProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobsRestartJobRequest) GetPreserveProgressOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveProgress) {
		return nil, false
	}
	return o.PreserveProgress, true
}

// HasPreserveProgress returns a boolean if a field has been set.
func (o *JobsRestartJobRequest) HasPreserveProgress() bool {
	if o != nil && !IsNil(o.PreserveProgress) {
		return true
	}

	return false
}

// SetPreserveProgress gets a reference to the given bool and assigns it to the PreserveProgress field.
func (o *JobsRestartJobRequest) SetPreserveProgress(v bool) {
	o.PreserveProgress = &v
}

func (o JobsRestartJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobsRestartJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Force) {
		toSerialize["force"] = o.Force
	}
	if !IsNil(o.PreserveProgress) {
		toSerialize["preserve_progress"] = o.PreserveProgress
	}
	return toSerialize, nil
}

type NullableJobsRestartJobRequest struct {
	value *JobsRestartJobRequest
	isSet bool
}

func (v NullableJobsRestartJobRequest) Get() *JobsRestartJobRequest {
	return v.value
}

func (v *NullableJobsRestartJobRequest) Set(val *JobsRestartJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableJobsRestartJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableJobsRestartJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobsRestartJobRequest(val *JobsRestartJobRequest) *NullableJobsRestartJobRequest {
	return &NullableJobsRestartJobRequest{value: val, isSet: true}
}

func (v NullableJobsRestartJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobsRestartJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
