/*
LeapOCR API

Provide your JWT token via the `Authorization` header. Example: Authorization: Bearer <token>

API version: v1
Contact: support@leapocr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
)

// checks if the AnalyticsJobTimeseriesPoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalyticsJobTimeseriesPoint{}

// AnalyticsJobTimeseriesPoint struct for AnalyticsJobTimeseriesPoint
type AnalyticsJobTimeseriesPoint struct {
	ActiveJobs           *int32   `json:"active_jobs,omitempty"`
	AvgCompletionSeconds *float32 `json:"avg_completion_seconds,omitempty"`
	Bucket               *string  `json:"bucket,omitempty"`
	CompletedJobs        *int32   `json:"completed_jobs,omitempty"`
	CreditsConsumed      *int32   `json:"credits_consumed,omitempty"`
	FailedJobs           *int32   `json:"failed_jobs,omitempty"`
	ProcessedPages       *int32   `json:"processed_pages,omitempty"`
	TotalJobs            *int32   `json:"total_jobs,omitempty"`
	TotalPages           *int32   `json:"total_pages,omitempty"`
}

// NewAnalyticsJobTimeseriesPoint instantiates a new AnalyticsJobTimeseriesPoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalyticsJobTimeseriesPoint() *AnalyticsJobTimeseriesPoint {
	this := AnalyticsJobTimeseriesPoint{}
	return &this
}

// NewAnalyticsJobTimeseriesPointWithDefaults instantiates a new AnalyticsJobTimeseriesPoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalyticsJobTimeseriesPointWithDefaults() *AnalyticsJobTimeseriesPoint {
	this := AnalyticsJobTimeseriesPoint{}
	return &this
}

// GetActiveJobs returns the ActiveJobs field value if set, zero value otherwise.
func (o *AnalyticsJobTimeseriesPoint) GetActiveJobs() int32 {
	if o == nil || IsNil(o.ActiveJobs) {
		var ret int32
		return ret
	}
	return *o.ActiveJobs
}

// GetActiveJobsOk returns a tuple with the ActiveJobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsJobTimeseriesPoint) GetActiveJobsOk() (*int32, bool) {
	if o == nil || IsNil(o.ActiveJobs) {
		return nil, false
	}
	return o.ActiveJobs, true
}

// HasActiveJobs returns a boolean if a field has been set.
func (o *AnalyticsJobTimeseriesPoint) HasActiveJobs() bool {
	if o != nil && !IsNil(o.ActiveJobs) {
		return true
	}

	return false
}

// SetActiveJobs gets a reference to the given int32 and assigns it to the ActiveJobs field.
func (o *AnalyticsJobTimeseriesPoint) SetActiveJobs(v int32) {
	o.ActiveJobs = &v
}

// GetAvgCompletionSeconds returns the AvgCompletionSeconds field value if set, zero value otherwise.
func (o *AnalyticsJobTimeseriesPoint) GetAvgCompletionSeconds() float32 {
	if o == nil || IsNil(o.AvgCompletionSeconds) {
		var ret float32
		return ret
	}
	return *o.AvgCompletionSeconds
}

// GetAvgCompletionSecondsOk returns a tuple with the AvgCompletionSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsJobTimeseriesPoint) GetAvgCompletionSecondsOk() (*float32, bool) {
	if o == nil || IsNil(o.AvgCompletionSeconds) {
		return nil, false
	}
	return o.AvgCompletionSeconds, true
}

// HasAvgCompletionSeconds returns a boolean if a field has been set.
func (o *AnalyticsJobTimeseriesPoint) HasAvgCompletionSeconds() bool {
	if o != nil && !IsNil(o.AvgCompletionSeconds) {
		return true
	}

	return false
}

// SetAvgCompletionSeconds gets a reference to the given float32 and assigns it to the AvgCompletionSeconds field.
func (o *AnalyticsJobTimeseriesPoint) SetAvgCompletionSeconds(v float32) {
	o.AvgCompletionSeconds = &v
}

// GetBucket returns the Bucket field value if set, zero value otherwise.
func (o *AnalyticsJobTimeseriesPoint) GetBucket() string {
	if o == nil || IsNil(o.Bucket) {
		var ret string
		return ret
	}
	return *o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsJobTimeseriesPoint) GetBucketOk() (*string, bool) {
	if o == nil || IsNil(o.Bucket) {
		return nil, false
	}
	return o.Bucket, true
}

// HasBucket returns a boolean if a field has been set.
func (o *AnalyticsJobTimeseriesPoint) HasBucket() bool {
	if o != nil && !IsNil(o.Bucket) {
		return true
	}

	return false
}

// SetBucket gets a reference to the given string and assigns it to the Bucket field.
func (o *AnalyticsJobTimeseriesPoint) SetBucket(v string) {
	o.Bucket = &v
}

// GetCompletedJobs returns the CompletedJobs field value if set, zero value otherwise.
func (o *AnalyticsJobTimeseriesPoint) GetCompletedJobs() int32 {
	if o == nil || IsNil(o.CompletedJobs) {
		var ret int32
		return ret
	}
	return *o.CompletedJobs
}

// GetCompletedJobsOk returns a tuple with the CompletedJobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsJobTimeseriesPoint) GetCompletedJobsOk() (*int32, bool) {
	if o == nil || IsNil(o.CompletedJobs) {
		return nil, false
	}
	return o.CompletedJobs, true
}

// HasCompletedJobs returns a boolean if a field has been set.
func (o *AnalyticsJobTimeseriesPoint) HasCompletedJobs() bool {
	if o != nil && !IsNil(o.CompletedJobs) {
		return true
	}

	return false
}

// SetCompletedJobs gets a reference to the given int32 and assigns it to the CompletedJobs field.
func (o *AnalyticsJobTimeseriesPoint) SetCompletedJobs(v int32) {
	o.CompletedJobs = &v
}

// GetCreditsConsumed returns the CreditsConsumed field value if set, zero value otherwise.
func (o *AnalyticsJobTimeseriesPoint) GetCreditsConsumed() int32 {
	if o == nil || IsNil(o.CreditsConsumed) {
		var ret int32
		return ret
	}
	return *o.CreditsConsumed
}

// GetCreditsConsumedOk returns a tuple with the CreditsConsumed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsJobTimeseriesPoint) GetCreditsConsumedOk() (*int32, bool) {
	if o == nil || IsNil(o.CreditsConsumed) {
		return nil, false
	}
	return o.CreditsConsumed, true
}

// HasCreditsConsumed returns a boolean if a field has been set.
func (o *AnalyticsJobTimeseriesPoint) HasCreditsConsumed() bool {
	if o != nil && !IsNil(o.CreditsConsumed) {
		return true
	}

	return false
}

// SetCreditsConsumed gets a reference to the given int32 and assigns it to the CreditsConsumed field.
func (o *AnalyticsJobTimeseriesPoint) SetCreditsConsumed(v int32) {
	o.CreditsConsumed = &v
}

// GetFailedJobs returns the FailedJobs field value if set, zero value otherwise.
func (o *AnalyticsJobTimeseriesPoint) GetFailedJobs() int32 {
	if o == nil || IsNil(o.FailedJobs) {
		var ret int32
		return ret
	}
	return *o.FailedJobs
}

// GetFailedJobsOk returns a tuple with the FailedJobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsJobTimeseriesPoint) GetFailedJobsOk() (*int32, bool) {
	if o == nil || IsNil(o.FailedJobs) {
		return nil, false
	}
	return o.FailedJobs, true
}

// HasFailedJobs returns a boolean if a field has been set.
func (o *AnalyticsJobTimeseriesPoint) HasFailedJobs() bool {
	if o != nil && !IsNil(o.FailedJobs) {
		return true
	}

	return false
}

// SetFailedJobs gets a reference to the given int32 and assigns it to the FailedJobs field.
func (o *AnalyticsJobTimeseriesPoint) SetFailedJobs(v int32) {
	o.FailedJobs = &v
}

// GetProcessedPages returns the ProcessedPages field value if set, zero value otherwise.
func (o *AnalyticsJobTimeseriesPoint) GetProcessedPages() int32 {
	if o == nil || IsNil(o.ProcessedPages) {
		var ret int32
		return ret
	}
	return *o.ProcessedPages
}

// GetProcessedPagesOk returns a tuple with the ProcessedPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsJobTimeseriesPoint) GetProcessedPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.ProcessedPages) {
		return nil, false
	}
	return o.ProcessedPages, true
}

// HasProcessedPages returns a boolean if a field has been set.
func (o *AnalyticsJobTimeseriesPoint) HasProcessedPages() bool {
	if o != nil && !IsNil(o.ProcessedPages) {
		return true
	}

	return false
}

// SetProcessedPages gets a reference to the given int32 and assigns it to the ProcessedPages field.
func (o *AnalyticsJobTimeseriesPoint) SetProcessedPages(v int32) {
	o.ProcessedPages = &v
}

// GetTotalJobs returns the TotalJobs field value if set, zero value otherwise.
func (o *AnalyticsJobTimeseriesPoint) GetTotalJobs() int32 {
	if o == nil || IsNil(o.TotalJobs) {
		var ret int32
		return ret
	}
	return *o.TotalJobs
}

// GetTotalJobsOk returns a tuple with the TotalJobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsJobTimeseriesPoint) GetTotalJobsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalJobs) {
		return nil, false
	}
	return o.TotalJobs, true
}

// HasTotalJobs returns a boolean if a field has been set.
func (o *AnalyticsJobTimeseriesPoint) HasTotalJobs() bool {
	if o != nil && !IsNil(o.TotalJobs) {
		return true
	}

	return false
}

// SetTotalJobs gets a reference to the given int32 and assigns it to the TotalJobs field.
func (o *AnalyticsJobTimeseriesPoint) SetTotalJobs(v int32) {
	o.TotalJobs = &v
}

// GetTotalPages returns the TotalPages field value if set, zero value otherwise.
func (o *AnalyticsJobTimeseriesPoint) GetTotalPages() int32 {
	if o == nil || IsNil(o.TotalPages) {
		var ret int32
		return ret
	}
	return *o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsJobTimeseriesPoint) GetTotalPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalPages) {
		return nil, false
	}
	return o.TotalPages, true
}

// HasTotalPages returns a boolean if a field has been set.
func (o *AnalyticsJobTimeseriesPoint) HasTotalPages() bool {
	if o != nil && !IsNil(o.TotalPages) {
		return true
	}

	return false
}

// SetTotalPages gets a reference to the given int32 and assigns it to the TotalPages field.
func (o *AnalyticsJobTimeseriesPoint) SetTotalPages(v int32) {
	o.TotalPages = &v
}

func (o AnalyticsJobTimeseriesPoint) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalyticsJobTimeseriesPoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActiveJobs) {
		toSerialize["active_jobs"] = o.ActiveJobs
	}
	if !IsNil(o.AvgCompletionSeconds) {
		toSerialize["avg_completion_seconds"] = o.AvgCompletionSeconds
	}
	if !IsNil(o.Bucket) {
		toSerialize["bucket"] = o.Bucket
	}
	if !IsNil(o.CompletedJobs) {
		toSerialize["completed_jobs"] = o.CompletedJobs
	}
	if !IsNil(o.CreditsConsumed) {
		toSerialize["credits_consumed"] = o.CreditsConsumed
	}
	if !IsNil(o.FailedJobs) {
		toSerialize["failed_jobs"] = o.FailedJobs
	}
	if !IsNil(o.ProcessedPages) {
		toSerialize["processed_pages"] = o.ProcessedPages
	}
	if !IsNil(o.TotalJobs) {
		toSerialize["total_jobs"] = o.TotalJobs
	}
	if !IsNil(o.TotalPages) {
		toSerialize["total_pages"] = o.TotalPages
	}
	return toSerialize, nil
}

type NullableAnalyticsJobTimeseriesPoint struct {
	value *AnalyticsJobTimeseriesPoint
	isSet bool
}

func (v NullableAnalyticsJobTimeseriesPoint) Get() *AnalyticsJobTimeseriesPoint {
	return v.value
}

func (v *NullableAnalyticsJobTimeseriesPoint) Set(val *AnalyticsJobTimeseriesPoint) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalyticsJobTimeseriesPoint) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalyticsJobTimeseriesPoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalyticsJobTimeseriesPoint(val *AnalyticsJobTimeseriesPoint) *NullableAnalyticsJobTimeseriesPoint {
	return &NullableAnalyticsJobTimeseriesPoint{value: val, isSet: true}
}

func (v NullableAnalyticsJobTimeseriesPoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalyticsJobTimeseriesPoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
