/*
LeapOCR API

Provide your JWT token via the `Authorization` header. Example: Authorization: Bearer <token>

API version: v1
Contact: support@leapocr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
)

// checks if the AuthAuthResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthAuthResponse{}

// AuthAuthResponse struct for AuthAuthResponse
type AuthAuthResponse struct {
	Message *string     `json:"message,omitempty"`
	Status  *string     `json:"status,omitempty"`
	User    interface{} `json:"user,omitempty"`
}

// NewAuthAuthResponse instantiates a new AuthAuthResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthAuthResponse() *AuthAuthResponse {
	this := AuthAuthResponse{}
	return &this
}

// NewAuthAuthResponseWithDefaults instantiates a new AuthAuthResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthAuthResponseWithDefaults() *AuthAuthResponse {
	this := AuthAuthResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AuthAuthResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthAuthResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AuthAuthResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AuthAuthResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AuthAuthResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthAuthResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AuthAuthResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AuthAuthResponse) SetStatus(v string) {
	o.Status = &v
}

// GetUser returns the User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuthAuthResponse) GetUser() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuthAuthResponse) GetUserOk() (*interface{}, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return &o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *AuthAuthResponse) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given interface{} and assigns it to the User field.
func (o *AuthAuthResponse) SetUser(v interface{}) {
	o.User = v
}

func (o AuthAuthResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthAuthResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableAuthAuthResponse struct {
	value *AuthAuthResponse
	isSet bool
}

func (v NullableAuthAuthResponse) Get() *AuthAuthResponse {
	return v.value
}

func (v *NullableAuthAuthResponse) Set(val *AuthAuthResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthAuthResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthAuthResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthAuthResponse(val *AuthAuthResponse) *NullableAuthAuthResponse {
	return &NullableAuthAuthResponse{value: val, isSet: true}
}

func (v NullableAuthAuthResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthAuthResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
